### ISSUE TITLE
Enterprise won't build with gcc >= 4.7

### ISSUE THREAD

**Issue by YorikSar** [SevenBits/Enterprise#28]
I've got a lot of errors like this:

    /usr/include/efi/x86_64/efibind.h:88:1: error: unknown type name ‘uint64_t’

As per [LKML thread] (https://lkml.org/lkml/2012/6/28/523) GCC stopped implicitly including `<stdint.h>` since 4.7, so `efibind.h` fails. I've added `#include <stdint.h>` to every `.c` file and it compiled, but I think there should be a better more general way to handle it.

**Comment by SevenBits** [comment]
That error is from `GNU-EFI`, a library used by Enterprise; it is not from Enterprise itself. I would recommend handling it upstream.
